KnowledgeTestingSystem.PL/Controllers/TestController.cs
using KnowledgeTestingSystem.BL.DTO;
using KnowledgeTestingSystem.BL.Infrastructure;
using KnowledgeTestingSystem.BL.Interfaces;
using KnowledgeTestingSystem.PL.Mapper;
using KnowledgeTestingSystem.PL.Models.Test;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KnowledgeTestingSystem.PL.Controllers
{
    public class TestController : Controller
    {
        private CreateTestMapper testMapper;
        private ITestService testService;

        //ctor
        public TestController(ITestService service)
        {
            testService = service;
        }

        // GET: Test
        //public ActionResult Index()
        //{
        //    return View();
        //}

        [Authorize]
        // GET: Test/Create
        public ActionResult Create()
        {
            CreateTestModel model = new CreateTestModel();
            return View(model);
        }

        // POST: Test/Create
        [Authorize]
        [HttpPost]
        public ActionResult Create(CreateTestModel model)
        {
            if (ModelState.IsValid)
            {
                testMapper = new CreateTestMapper();
                var testDto = testMapper.MapCreateTestModelToCreateTestDTO(model, User.Identity.Name);
                OperationDetails operationDetails = testService.CreateTest(testDto);
                if (operationDetails.Succedeed)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError(operationDetails.Property, operationDetails.Message);
                }
            }
            return View(model);

        }

        [Authorize]
        public ViewResult PassTheTest(string testName)
        {
            var test = testService.GetTest(testName,User.Identity.Name);
            if (test != null)
            {
                PassTheTestModelMapper mapper = new PassTheTestModelMapper();
                var passTheTestModel = mapper.MapGetTestDTOToPassTheTestModel(test);
                return View(passTheTestModel);
            }
            //throw new HttpException(404, "Page Not Found");
            return View("~/Views/Home/Index.cshtml");
        }

        [Authorize]
        [HttpPost]
        public ViewResult PassTheTest(PassTheTestModel passTheTestModel)
        {
            PassTheTestModelMapper mapper = new PassTheTestModelMapper();
            testService.PassTest(mapper.MapPassTheTestModelToPassTestDTO(passTheTestModel), User.Identity.Name);
            
            return View("~/Views/Home/Index.cshtml");
        }


        public ViewResult QuestionEditorRow()
        {
            var element = new TestQuestionModel();
            return View("AddQuestionPartial", element);
        }


        public ActionResult Search()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Search(string filter)
        {
            ViewBag.filter = filter;
            return View();
        }


        public ActionResult SearchTest(string filter)
        {
            ICollection<SearchTestDTO> listOfTestNames;
            if (User.Identity.IsAuthenticated)
            {
                listOfTestNames = testService.FindTestWhichContainText(filter, User.Identity.Name);
            }
            else
            {
                listOfTestNames = testService.FindTestWhichContainText(filter);
            }
            SearchTestMapper searchTestMapper = new SearchTestMapper();
            var listOfSearchTestModel = searchTestMapper.MapSearchTestDTOToSearchTestModel(listOfTestNames);
            return View("SearchTestPartial", listOfSearchTestModel);

        }

        [Authorize]
        public ActionResult Subscribe(string testName)
        {
            OperationDetails opDet = testService.SubscribeToTest(testName, User.Identity.Name);
            return Redirect(Request.UrlReferrer.ToString());
        }

        [Authorize]
        public ActionResult Subscriptions()
        {
            UserSubscribedTestsMapper mapper = new UserSubscribedTestsMapper();
            List<UserSubscribedTestsModel> userSubscribedTests = mapper.MapUserSubscribtionsDTOToUserSubscribedTestsModel(testService.UsersSubscriptions(User.Identity.Name)).ToList();
            return View(userSubscribedTests);
        }

    }
}

KnowledgeTestingSystem.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Knowledge Test System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (User.IsInRole("admin"))
                    {
                        <li>@Html.ActionLink("Admin", "About", "Home")</li>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Create Test", "Create", "Test")</li>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Subscriptions", "Subscriptions", "Test")</li>
                    }
                    <li>@Html.ActionLink("Search test", "Search", "Test")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Log in", "Login", "Account")</li>
                        <li>@Html.ActionLink("Registter", "Register", "Account")</li>
                    }
                    else
                    {
                        <li>
                            <a>Hi, @User.Identity.Name</a>
                        </li>
                        <li>@Html.ActionLink("Log out", "Logout", "Account")</li>
                    }

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Knowledge Testing System</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/scripts")
    @RenderSection("scripts", required: false)
</body>
</html>